brain_wash/urls.py
from django.urls import path
from django.views import generic

app_name = 'brain_wash'
urlpatterns = [
    path('', generic.TemplateView.as_view(template_name='brain_wash/home.html'), name='home'),
]

brain_wash/models.py
from django.db import models

# Create your models here.

brain_wash/views.py
from django.shortcuts import render

# Create your views here.

brain_wash/templates/brain_wash/base.html
{% load static %}
{# a sample base.html file #}
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Brain Wash{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="reading drill">
    <meta name="author" content="mrtuttle">

    <link rel="home" href="/" />
    {% block brain_wash_css %}{% endblock %}
    {% block brain_wash_js %}{% endblock %}

    <link rel="index" href="/" />

  </head>
  <body>
    <h1>Brain Wash</h1>
    <div class="nav_main">
      <a href="/">home</a>
      <a href="{% url 'brain_wash:home' %}">brain wash</a>
      {% block nav_main %}
      {% endblock %}
    </div class="nav_main">

    <div class="content_main">
      {% block brain_wash_content %}
      {% endblock %}
    </div class="content_main">

    <div class="footer_main">
      <p>GORIRIDERYOUMOTHERFU!!!</p>
    </div class="footer_main">
  </body>
</html>

brain_wash/templates/brain_wash/home.html
{% extends "brain_wash/base.html" %}
{% load static %}

{% block brain_wash_css %}
    <link rel="stylesheet" href="{% static 'brain_wash/css/app.css' %}" />
{% endblock %}

{% block brain_wash_js %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
    <script src="{% static 'brain_wash/js/app.js' %}" ></script>
{% endblock %}

{% block brain_wash_content %}
<div id="brain_wash">
  <p></p>
  <div>
    <textarea id="word_source" placeholder="Paste text you want displayed into this textarea to get started."></textarea>
    <button onclick="setup_paragraph_bank()">Update Text</button>
    paragraph: <span id="paragraph_index">5</span>
    <button onclick="previous_paragraph()">Previous Paragraph</button>
    <button onclick="next_paragraph()">Next Paragraph</button>
    wpm: <span id="wpm">5</span>
    <button onclick="wpm_up()">+</button>
    <button onclick="wpm_down()">-</button>
    <button onclick="toggle_paused()"><span id="paused">True</span></button>
  </div>
  <div id="app_display" tabindex="0">
    <div id="word_holder">womp womp</div>
    <div id="paragraph_holder"></div>
  </div id="app_display">
</div id="brain_wash">
{% endblock brain_wash_content %}